import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';
import { NgxDocViewerModule } from 'ngx-doc-viewer';
import { InfiniteScrollModule } from 'ngx-infinite-scroll';
import { ContactModule } from '../contact/contact.module';
import { EventsModule } from '../events/events.module';
import { ExemptionsModule } from '../exemptions/exemptions.module';
import { ParcelInfoGrievancesModule } from '../parcel-info-grievances/parcel-info-grievances.module';
import { SharedModule } from '../shared/shared.module';
import {
  ParcelInfoGrievancesFinalExemptionNoteComponent,
  ParcelInfoSmallClaimsAddComponent,
  ParcelInfoSmallClaimsAppraisalsDetailsComponent,
  ParcelInfoSmallClaimsAppraisalsFooterComponent,
  ParcelInfoSmallClaimsAppraisalsFormDialogComponent,
  ParcelInfoSmallClaimsAppraisalsOverviewComponent,
  ParcelInfoSmallClaimsAppraisalsTableComponent,
  ParcelInfoSmallClaimsAppraiserModalComponent,
  ParcelInfoSmallClaimsComplaintReasonTableComponent,
  ParcelInfoSmallClaimsDetailsComponent,
  ParcelInfoSmallClaimsDocumentsFooterComponent,
  ParcelInfoSmallClaimsDocumentsOverviewComponent,
  ParcelInfoSmallClaimsDocumentsPreviewModalComponent,
  ParcelInfoSmallClaimsDocumentsTableComponent,
  ParcelInfoSmallClaimsDocumentsUploadModalComponent,
  ParcelInfoSmallClaimsEventDialogComponent,
  ParcelInfoSmallClaimsExemptionsTableComponent,
  ParcelInfoSmallClaimsFooterComponent,
  ParcelInfoSmallClaimsFormComponent,
  ParcelInfoSmallClaimsGrievancesSelectTableComponent,
  ParcelInfoSmallClaimsInfoComponent,
  ParcelInfoSmallClaimsNotesFooterComponent,
  ParcelInfoSmallClaimsNotesOverviewComponent,
  ParcelInfoSmallClaimsNotesTableComponent,
  ParcelInfoSmallClaimsOverallFormComponent,
  ParcelInfoSmallClaimsOverviewComponent,
  ParcelInfoSmallClaimsOwnerFormComponent,
  ParcelInfoSmallClaimsParcelInformationAtTimeOfSmallClaimsComponent,
  ParcelInfoSmallClaimsParcelInformationComponent,
  ParcelInfoSmallClaimsParcelInformationSalesComponent,
  ParcelInfoSmallClaimsParcelInformationSpecialDistrictsComponent,
  ParcelInfoSmallClaimsPetitionerFormComponent,
  ParcelInfoSmallClaimsPriorCurrentInfoComponent,
  ParcelInfoSmallClaimsResultsEventsTableComponent,
  ParcelInfoSmallClaimsResultsFinalExemptionsTableComponent,
  ParcelInfoSmallClaimsResultsOverallComponent,
  ParcelInfoSmallClaimsResultsOverviewComponent,
  ParcelInfoSmallClaimsResultsPetitionersReasonComponent,
  ParcelInfoSmallClaimsSelectGrievancesComponent,
  ParcelInfoSmallClaimsTableComponent,
  ParcelInfoSmallClaimsTotalsFormComponent,
} from './components';
import { FullMarketFormattedFieldPipe } from './pipes';
import {
  featureKey,
  ParcelInfoSmallClaimsAddEffects,
  ParcelInfoSmallClaimsAppraisalsEffects,
  ParcelInfoSmallClaimsComplaintReasonsEffects,
  ParcelInfoSmallClaimsCurrentEventEffects,
  ParcelInfoSmallClaimsDetailsEffects,
  ParcelInfoSmallClaimsDocumentsEffects,
  ParcelInfoSmallClaimsDocumentsPreviewEffects,
  ParcelInfoSmallClaimsDocumentsUploadEffects,
  ParcelInfoSmallClaimsEffects,
  ParcelInfoSmallClaimsEventsEffects,
  ParcelInfoSmallClaimsExemptionsEffects,
  ParcelInfoSmallClaimsNotesEffects,
  ParcelInfoSmallClaimsParcelInformationAtTimeOfSmallClaimsEffects,
  ParcelInfoSmallClaimsParcelInformationSalesEffects,
  ParcelInfoSmallClaimsParcelInformationSpecialDistrictsEffects,
  ParcelInfoSmallClaimsResultsEffects,
  reducers,
} from './store';

@NgModule({
  declarations: [
    ParcelInfoSmallClaimsTableComponent,
    ParcelInfoSmallClaimsInfoComponent,
    ParcelInfoSmallClaimsOverviewComponent,
    ParcelInfoSmallClaimsDetailsComponent,
    ParcelInfoSmallClaimsResultsOverviewComponent,
    ParcelInfoSmallClaimsNotesOverviewComponent,
    ParcelInfoSmallClaimsOverallFormComponent,
    ParcelInfoSmallClaimsOwnerFormComponent,
    ParcelInfoSmallClaimsPetitionerFormComponent,
    ParcelInfoSmallClaimsExemptionsTableComponent,
    ParcelInfoSmallClaimsFooterComponent,
    ParcelInfoSmallClaimsFormComponent,
    ParcelInfoSmallClaimsTotalsFormComponent,
    ParcelInfoSmallClaimsAddComponent,
    ParcelInfoSmallClaimsSelectGrievancesComponent,
    ParcelInfoSmallClaimsResultsPetitionersReasonComponent,
    ParcelInfoSmallClaimsParcelInformationComponent,
    ParcelInfoSmallClaimsParcelInformationAtTimeOfSmallClaimsComponent,
    ParcelInfoSmallClaimsParcelInformationSalesComponent,
    ParcelInfoSmallClaimsParcelInformationSpecialDistrictsComponent,
    FullMarketFormattedFieldPipe,
    ParcelInfoSmallClaimsGrievancesSelectTableComponent,
    ParcelInfoSmallClaimsNotesFooterComponent,
    ParcelInfoSmallClaimsNotesOverviewComponent,
    ParcelInfoSmallClaimsNotesTableComponent,
    ParcelInfoSmallClaimsDocumentsFooterComponent,
    ParcelInfoSmallClaimsDocumentsPreviewModalComponent,
    ParcelInfoSmallClaimsDocumentsOverviewComponent,
    ParcelInfoSmallClaimsDocumentsTableComponent,
    ParcelInfoSmallClaimsDocumentsUploadModalComponent,
    ParcelInfoSmallClaimsPriorCurrentInfoComponent,
    ParcelInfoSmallClaimsResultsOverallComponent,
    ParcelInfoSmallClaimsResultsFinalExemptionsTableComponent,
    ParcelInfoSmallClaimsResultsPetitionersReasonComponent,
    ParcelInfoSmallClaimsResultsEventsTableComponent,
    ParcelInfoSmallClaimsEventDialogComponent,
    ParcelInfoSmallClaimsAppraisalsOverviewComponent,
    ParcelInfoSmallClaimsAppraisalsTableComponent,
    ParcelInfoSmallClaimsAppraisalsDetailsComponent,
    ParcelInfoSmallClaimsAppraisalsFooterComponent,
    ParcelInfoSmallClaimsAppraisalsFormDialogComponent,
    ParcelInfoGrievancesFinalExemptionNoteComponent,
    ParcelInfoSmallClaimsAppraiserModalComponent,
    ParcelInfoSmallClaimsComplaintReasonTableComponent,
  ],
  imports: [
    CommonModule,
    SharedModule,
    NgxDocViewerModule,
    StoreModule.forFeature(featureKey, reducers),
    EffectsModule.forFeature([
      ParcelInfoSmallClaimsEffects,
      ParcelInfoSmallClaimsDetailsEffects,
      ParcelInfoSmallClaimsExemptionsEffects,
      ParcelInfoSmallClaimsAddEffects,
      ParcelInfoSmallClaimsNotesEffects,
      ParcelInfoSmallClaimsResultsEffects,
      ParcelInfoSmallClaimsEventsEffects,
      ParcelInfoSmallClaimsParcelInformationAtTimeOfSmallClaimsEffects,
      ParcelInfoSmallClaimsDocumentsEffects,
      ParcelInfoSmallClaimsDocumentsUploadEffects,
      ParcelInfoSmallClaimsDocumentsPreviewEffects,
      ParcelInfoSmallClaimsParcelInformationSalesEffects,
      ParcelInfoSmallClaimsParcelInformationSpecialDistrictsEffects,
      ParcelInfoSmallClaimsAppraisalsEffects,
      ParcelInfoSmallClaimsCurrentEventEffects,
      ParcelInfoSmallClaimsComplaintReasonsEffects,
    ]),
    ContactModule,
    InfiniteScrollModule,
    EventsModule,
    ParcelInfoGrievancesModule,
    ExemptionsModule,
  ],
  exports: [ParcelInfoSmallClaimsTableComponent, ParcelInfoSmallClaimsInfoComponent],
})
export class ParcelInfoSmallClaimsModule {}
